version: '3'

services:
  # PostgreSQL database
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    networks:
      - app-network

  # Redis server
  redis:
    image: 'redis:latest'
    ports:
      - '6380:6379'
    networks:
      - app-network

  # Nest application
  app:
    build: .
    command: npm run start:dev
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
